### ISSUE TITLE
关于list页面的问题

### ISSUE THREAD

**Issue by VachelHU** [liu946/lvsecunzhen#2]
1、路由有问题，获取了modelname还需要获取id才行，参考严寒项目，这个项目相当于我多要一个modelname将其区分而已
2、获取表格列表有问题，在严寒项目中没有找到获取的接口，绿色项目的获取了我写了一个demo出来，但并不知道返回的json结构是什么样的，demo是id，title和修改button

**Comment by liu946** [comment]
已解决
