### ISSUE TITLE
2015年09月27日 测试

### ISSUE THREAD

**Issue by liu946** [liu946/lvsecunzhen#3]
1. 后台字段为null前台应显示为空字符串
2. 部分字段保存出现问题，主要集中在单选、其他填写数据保存不上
3. 严寒没有主页可以，绿色应有主页转到三个list页面，应有办法转到dbgenerator页面
4. 严寒 edit 进入时没有同步数据
5. 单位没有显示

**Comment by VachelHU** [comment]
1、严寒的bug已经解决，测试一下
2、绿色城镇的ajax请求的后台问题还在，你处理好再试试前端还有没有问题
