### ISSUE TITLE
2015年09月29日测试

### ISSUE THREAD

**Issue by liu946** [liu946/lvsecunzhen#4]
1. 其他选中填写之后不应隐藏
2. 其他保存之后再取回数据之前打的钩就没了
3. 镇区村庄两个选项保存1、2不是字符串，因为这是判断字段
4. 注意村庄比镇区少几个属性，在选择了村庄之后应该不予显示和发送
5. 两个选父类的菜单获取存在问题，无法显示
6. 部分字段应为选择而不是填写
7. 测试全部字段填写之后仍无法提交，注意有年份的字段是不一定要全部填写的
8. 制作主页（去向3个list页面和dbgenerator页面），其他页面应该有回主页link

**Comment by VachelHU** [comment]
1、问题解决
2、问题解决
3、存入的value是“1”，‘2’这个形式的，后台应该可以处理强转成需要的number型
4、问题没明白。。。？
5、在镇区或村庄，住户这两个里面，index/get/modelname获取不到任何信息，返回空数组
8、主页已经有了，访问/下就是
9、总之，修改index/get/modelname问题后基本bug没有了，这个问题导致了5问题的出现和表单中select的不能选择，解决之后，基本没什么大问题了

**Comment by liu946** [comment]
3 . 待测
4 . 看一下文档那张图
5 . url为input/get/modelname，另需要先自行存入数据库数据

**Comment by VachelHU** [comment]
对，就是存了数据进去了，但是获取回来还是空，点击添加按钮编号都到2，3，4了，4条数据没有返回来
